# Generated by Django 5.0.6 on 2024-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('uid', models.TextField(blank=True, null=True)),
                ('private_key', models.TextField(blank=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('account', models.TextField(blank=True)),
            ],
        ),
    ]
