# Generated by Django 5.0.6 on 2024-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True)),
                ('result', models.FloatField(blank=True)),
                ('locked', models.FloatField(blank=True)),
            ],
        ),
    ]
