# Generated by Django 4.2.13 on 2024-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_balance_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
